### ISSUE TITLE
Unit labels missing in strat column export

### ISSUE THREAD

**Issue by jllancaster** [laccore/coretools#16]
Hi there,

We seem to be running into an issue where Unit intervals and labels are not showing up in our strat composite column exports. Any thoughts on where we might be going wrong?

Thanks!

![image](https://github.com/user-attachments/assets/77311b85-3ae0-4590-bfca-dd7b29e90363)

**Comment by sorghumking** [comment]
Thanks for adding an issue! You're not at fault here, this is definitely a PSICAT bug. When generating strat columns with the File > Create New > Composite Section (Stratigraphic Column)... option, only certain model types are included. Units are not among those model types at present. This is a lingering oversight from development. A new 1.2.3 release is coming early next week, in which this bug will be addressed.

Incidentally, in the screenshot of your strat column it looks like it contains Images (far left column, very narrow), is that correct? Images are another model type excluded from the generation of composite sections in 1.2.2*. So I'm curious as to why you have images in your strat, unless you manually added them to the underlying XML data?

*Another oversight from development, although Images are a bit trickier than Units in that here at the CSD Faciliity our images always include color cards at the bottom of the core section, which complicates composite section generation for reasons I'll bore you with later if you're really interested!

**Comment by sorghumking** [comment]
This issue should be resolved in [v1.2.3](https://github.com/laccore/coretools/releases/tag/1.2.3). Apologies for the delayed release of this build!

**Comment by jllancaster** [comment]
> Thanks for adding an issue! You're not at fault here, this is definitely a PSICAT bug. When generating strat columns with the File > Create New > Composite Section (Stratigraphic Column)... option, only certain model types are included. Units are not among those model types at present. This is a lingering oversight from development. A new 1.2.3 release is coming early next week, in which this bug will be addressed.
> 
> Incidentally, in the screenshot of your strat column it looks like it contains Images (far left column, very narrow), is that correct? Images are another model type excluded from the generation of composite sections in 1.2.2*. So I'm curious as to why you have images in your strat, unless you manually added them to the underlying XML data?
> 
> *Another oversight from development, although Images are a bit trickier than Units in that here at the CSD Faciliity our images always include color cards at the bottom of the core section, which complicates composite section generation for reasons I'll bore you with later if you're really interested!

Hi there, thanks for fixing this, I missed that you responded here somehow. Have been testing the new version and all seems to be working well regarding the unit labels.

Regarding images, yes we were hacking it a bit to add these to the composite column by modifying the xml files. We've been clipping our images to remove extra stuff at the ends of the cores, so it seems to work okay, its just dang difficult to see the images in the strat column export, so I've actually dropped that from the final export.

**Comment by sorghumking** [comment]
Glad to hear the Units issue is fixed, and thanks for testing the new version!

PSICAT currently insists on displaying Images at the correct aspect ratio, so in any reasonably large strat column, they will be almost invisibly thin. Furthermore, they blow up the size of the exported PDF. For these reasons, we almost never include them in a strat. Individual section diagrams (File > Export > Diagram...) are better-suited to including Images.
