### ISSUE TITLE
Underscores in section names not compatible with splice interval table?

### ISSUE THREAD

**Issue by jllancaster** [laccore/coretools#17]
Hi there!

Is there a way to have a splice interval table work with section names entered with an underscore, as below?

![image](https://github.com/user-attachments/assets/8a43c891-cba0-426f-88f3-922a591ed22a)

Currently using the splice interval table according to the YouTube tutorial will not match with section names using underscores.

Thanks!

**Comment by sorghumking** [comment]
Not a present, but I can certainly take a look at supporting underscore-delimited section names in addition to hyphen-delimited. Especially since the ICDP naming convention typically uses underscores. Stay tuned!

**Comment by jllancaster** [comment]
Thanks! Yeah we are using ICDP format. For now, we can get the section metadata approach to work fine with our naming schemes. The SIT seemed like it would solve some problems for us so we were trying it out. Cheers and as always, thanks for this program.

**Comment by sorghumking** [comment]
SIT is certainly more versatile than plain Section Metadata. But also more complex and, frankly, clunkier in that it requires strict adherence to the IODP SIT format with separated section ID components that assume a hyphen delimiter.

There may be a quick-ish fix in PSICAT: prompting for a delimiter when the section metadata file is selected on File > New > Stratigraphic Column. If it's not too time-consuming I'll add that to the next release.

In the meantime, I'm glad to hear you're able to work around the hyphen requirement for now.

Let us know if there are other problems that can't be overcome with the SIT section metadata format, we may be able to address them in the near-term, and we'll certainly add them to the longer-term features list.

**Comment by sorghumking** [comment]
Supporting non-hyphen delimiters was straightforward. That option is now available in [the latest release (1.2.5)](https://github.com/laccore/coretools/releases/tag/1.2.5).
